name: Java CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Build with Gradle/Maven
      run: ./gradlew build  # Change to `mvn install` if using Maven instead of Gradle

    - name: Run tests
      run: ./gradlew test  # Change to `mvn test` if using Maven

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: build/test-results/test/  # Adjust path if needed for Maven or Gradle
